// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations.RealDb
{
    [DbContext(typeof(RealDbContext))]
    [Migration("20241205231618_SecondRealDbContextMigration")]
    partial class SecondRealDbContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingItemOutfit", b =>
                {
                    b.Property<Guid>("OutfitClothesClothingItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutfitsOutfitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutfitClothesClothingItemId", "OutfitsOutfitId");

                    b.HasIndex("OutfitsOutfitId");

                    b.ToTable("OutfitClothingItem", (string)null);
                });

            modelBuilder.Entity("WebApp.Models.Domain.ClothingItem", b =>
                {
                    b.Property<Guid>("ClothingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClothingType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClothingItemId");

                    b.ToTable("ClothingItems", (string)null);

                    b.HasDiscriminator<string>("ClothingType").HasValue("StandardClothingItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApp.Models.Domain.Outfit", b =>
                {
                    b.Property<Guid>("OutfitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutfitId");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("WebApp.Models.Domain.BottomLayerClothingItem", b =>
                {
                    b.HasBaseType("WebApp.Models.Domain.ClothingItem");

                    b.Property<string>("Design")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("BottomLayer");
                });

            modelBuilder.Entity("WebApp.Models.Domain.TopBaseClothingItem", b =>
                {
                    b.HasBaseType("WebApp.Models.Domain.ClothingItem");

                    b.Property<string>("Design")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ClothingItems", t =>
                        {
                            t.Property("Design")
                                .HasColumnName("TopBaseClothingItem_Design");
                        });

                    b.HasDiscriminator().HasValue("TopLayer");
                });

            modelBuilder.Entity("ClothingItemOutfit", b =>
                {
                    b.HasOne("WebApp.Models.Domain.ClothingItem", null)
                        .WithMany()
                        .HasForeignKey("OutfitClothesClothingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Domain.Outfit", null)
                        .WithMany()
                        .HasForeignKey("OutfitsOutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
